# Generated by Django 3.1.6 on 2021-02-10 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yokira_app_gg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('player_class', models.CharField(choices=[('SM', 'Samurai'), ('SH', 'Shinobi'), ('MK', 'Monk')], max_length=2)),
                ('backpack_contents', models.OneToOneField(default=yokira_app_gg.models.Backpack, on_delete=django.db.models.deletion.CASCADE, to='yokira_app_gg.backpack')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('min_atk', models.IntegerField()),
                ('max_atk', models.IntegerField()),
                ('min_def', models.IntegerField()),
                ('max_def', models.IntegerField()),
                ('item_type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='yokira_app_gg.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=20)),
                ('enemy_level', models.IntegerField(default=1)),
                ('min_atk', models.IntegerField()),
                ('max_atk', models.IntegerField()),
                ('min_def', models.IntegerField()),
                ('max_def', models.IntegerField()),
                ('enemy_image', models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, to='yokira_app_gg.enemyimage')),
                ('enemy_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='yokira_app_gg.enemytype')),
            ],
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_1', to='yokira_app_gg.equipment'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_2', to='yokira_app_gg.equipment'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_3', to='yokira_app_gg.equipment'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_4', to='yokira_app_gg.equipment'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_5', to='yokira_app_gg.equipment'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='slot_6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_slot_6', to='yokira_app_gg.equipment'),
        ),
    ]
