# Generated by Django 3.1.6 on 2021-02-08 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yokira_app_gg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_name', models.CharField(max_length=20)),
                ('enemy_type', models.CharField(max_length=20)),
                ('enemy_level', models.IntegerField(default=1)),
                ('min_atk', models.IntegerField()),
                ('max_atk', models.IntegerField()),
                ('min_def', models.IntegerField()),
                ('max_def', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('is_equipped', models.BooleanField(default=False)),
                ('min_atk', models.IntegerField()),
                ('max_atk', models.IntegerField()),
                ('min_def', models.IntegerField()),
                ('max_def', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('player_class', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
