# Generated by Django 3.1.6 on 2021-02-09 03:13

from django.db import migrations, models
import django.db.models.deletion
import yokira_app_gg.models


class Migration(migrations.Migration):

    dependencies = [
        ('yokira_app_gg', '0002_enemy_equipment_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_class',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_1', to='yokira_app_gg.equipment')),
                ('slot_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_2', to='yokira_app_gg.equipment')),
                ('slot_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_3', to='yokira_app_gg.equipment')),
                ('slot_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_4', to='yokira_app_gg.equipment')),
                ('slot_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_5', to='yokira_app_gg.equipment')),
                ('slot_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_slot_6', to='yokira_app_gg.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, to='yokira_app_gg.enemyimage'),
        ),
        migrations.AddField(
            model_name='player',
            name='backpack_contents',
            field=models.OneToOneField(default=yokira_app_gg.models.Backpack, on_delete=django.db.models.deletion.CASCADE, to='yokira_app_gg.backpack'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='yokira_app_gg.itemtype'),
        ),
    ]
