# Generated by Django 3.1.6 on 2021-02-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yokira_app_gg', '0003_auto_20210211_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemyimage',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
